-- V002__import_vogelklassen.sql
-- Vogelklassen aus Farbe.DB + unique SKL-Kombinationen aus Schaudaten

INSERT INTO vogelklasse (skl1, skl2, skl3, farbe1, farbe2, erstellt_am, version) VALUES
  ('1', '1', NULL, 'Hellgrün', NULL, CURRENT_TIMESTAMP, 0),
  ('1', '2', NULL, 'Graugrün', NULL, CURRENT_TIMESTAMP, 0),
  ('1', '3', NULL, 'Dunkelfarben Grün', NULL, CURRENT_TIMESTAMP, 0),
  ('10', '1', NULL, 'Rez. Schecke Grünreihe', NULL, CURRENT_TIMESTAMP, 0),
  ('10', '2', NULL, 'Rez. Schecke Blaureihe', NULL, CURRENT_TIMESTAMP, 0),
  ('11', '1', NULL, 'A Schecke Grünreihe', NULL, CURRENT_TIMESTAMP, 0),
  ('11', '2', NULL, 'A Schecke Blaureihe', NULL, CURRENT_TIMESTAMP, 0),
  ('12', '1', NULL, 'Spangle Grünreihe', NULL, CURRENT_TIMESTAMP, 0),
  ('12', '2', NULL, 'Spangle Blausreihe', NULL, CURRENT_TIMESTAMP, 0),
  ('12', '3', NULL, 'Dänische Spangle', NULL, CURRENT_TIMESTAMP, 0),
  ('13', '1', NULL, 'DF Spangle Gelb', NULL, CURRENT_TIMESTAMP, 0),
  ('13', '2', NULL, 'DF Spangle Weiß', NULL, CURRENT_TIMESTAMP, 0),
  ('14', '1', NULL, 'T. Clearbody Grünreihe', NULL, CURRENT_TIMESTAMP, 0),
  ('14', '2', NULL, 'T. Clearbody Blaureihe', NULL, CURRENT_TIMESTAMP, 0),
  ('15', '1', NULL, 'Grauflügel', NULL, CURRENT_TIMESTAMP, 0),
  ('15', '2', NULL, 'Hellflügel', NULL, CURRENT_TIMESTAMP, 0),
  ('16', '1', NULL, 'Easly Clearbody', NULL, CURRENT_TIMESTAMP, 0),
  ('16', '3', NULL, 'Konti Schecken', NULL, CURRENT_TIMESTAMP, 0),
  ('16', '4', NULL, 'Schwarzaugen', NULL, CURRENT_TIMESTAMP, 0),
  ('16', '5', NULL, 'Hauben', NULL, CURRENT_TIMESTAMP, 0),
  ('17', '1', NULL, 'Paare 1,2,3,4,5,6,11,12,13', NULL, CURRENT_TIMESTAMP, 0),
  ('17', '3', NULL, 'Kollektionen 1,2,3,4,5,6,11,12,13', NULL, CURRENT_TIMESTAMP, 0),
  ('18', '1', NULL, 'Neumutationen', NULL, CURRENT_TIMESTAMP, 0),
  ('19', NULL, NULL, 'Nicht Eingeliefert', NULL, CURRENT_TIMESTAMP, 0),
  ('2', '1', NULL, 'Hellblau', NULL, CURRENT_TIMESTAMP, 0),
  ('2', '2', NULL, 'Grau', NULL, CURRENT_TIMESTAMP, 0),
  ('2', '3', NULL, 'Dunkelfarben Blau', NULL, CURRENT_TIMESTAMP, 0),
  ('21', '1', NULL, 'Hellgrün', NULL, CURRENT_TIMESTAMP, 0),
  ('21', '2', NULL, 'Graugrün', NULL, CURRENT_TIMESTAMP, 0),
  ('21', '3', NULL, 'Dunkelfarben Grün', NULL, CURRENT_TIMESTAMP, 0),
  ('22', '1', NULL, 'Hellblau', NULL, CURRENT_TIMESTAMP, 0),
  ('22', '2', NULL, 'Grau', NULL, CURRENT_TIMESTAMP, 0),
  ('22', '3', NULL, 'Dunkelfarben Blau', NULL, CURRENT_TIMESTAMP, 0),
  ('23', '1', NULL, 'Zimt Grünreihe', NULL, CURRENT_TIMESTAMP, 0),
  ('23', '2', NULL, 'Zimt Blaureihe', NULL, CURRENT_TIMESTAMP, 0),
  ('24', '1', NULL, 'Zimt Opalin Grünreihe', NULL, CURRENT_TIMESTAMP, 0),
  ('24', '2', NULL, 'Zimt Opalin Blaureihe', NULL, CURRENT_TIMESTAMP, 0),
  ('25', '1', NULL, 'Opalin Grünreihe', NULL, CURRENT_TIMESTAMP, 0),
  ('25', '2', NULL, 'Opalin Blaureihe', NULL, CURRENT_TIMESTAMP, 0),
  ('26', '1', NULL, 'Gelbgesicht Normal', NULL, CURRENT_TIMESTAMP, 0),
  ('26', '2', NULL, 'Gelbgesicht Zimt', NULL, CURRENT_TIMESTAMP, 0),
  ('26', '3', NULL, 'Gelbgesicht Zimt Opalin', NULL, CURRENT_TIMESTAMP, 0),
  ('26', '4', NULL, 'Gelbgesicht Opalin', NULL, CURRENT_TIMESTAMP, 0),
  ('27', '1', NULL, 'Lutino', NULL, CURRENT_TIMESTAMP, 0),
  ('27', '2', NULL, 'Albino', NULL, CURRENT_TIMESTAMP, 0),
  ('28', '1', NULL, 'Lacewing Gelb', NULL, CURRENT_TIMESTAMP, 0),
  ('28', '2', NULL, 'Lacewing Weiß', NULL, CURRENT_TIMESTAMP, 0),
  ('29', '1', NULL, 'Aufghellt Gelb', NULL, CURRENT_TIMESTAMP, 0),
  ('29', '2', NULL, 'Aufgehellt Weiß', NULL, CURRENT_TIMESTAMP, 0),
  ('3', '1', NULL, 'Zimt Grünreihe', NULL, CURRENT_TIMESTAMP, 0),
  ('3', '2', NULL, 'Zimt Blaureihe', NULL, CURRENT_TIMESTAMP, 0),
  ('30', '1', NULL, 'Rez. Schecke Grünreihe', NULL, CURRENT_TIMESTAMP, 0),
  ('30', '2', NULL, 'Rez. Schecke Blaureihe', NULL, CURRENT_TIMESTAMP, 0),
  ('31', '1', NULL, 'A Schecke Grünreihe', NULL, CURRENT_TIMESTAMP, 0),
  ('31', '2', NULL, 'A Schecke Blaureihe', NULL, CURRENT_TIMESTAMP, 0),
  ('32', '1', NULL, 'Spangle Grünreihe', NULL, CURRENT_TIMESTAMP, 0),
  ('32', '2', NULL, 'Spangle Blausreihe', NULL, CURRENT_TIMESTAMP, 0),
  ('32', '3', NULL, 'Dänische Spangle', NULL, CURRENT_TIMESTAMP, 0),
  ('33', '1', NULL, 'DF Spangle Gelb', NULL, CURRENT_TIMESTAMP, 0),
  ('33', '2', NULL, 'DF Spangle Weiß', NULL, CURRENT_TIMESTAMP, 0),
  ('34', '1', NULL, 'T. Clearbody Grünreihe', NULL, CURRENT_TIMESTAMP, 0),
  ('34', '2', NULL, 'T. Clearbody Blaureihe', NULL, CURRENT_TIMESTAMP, 0),
  ('35', '1', NULL, 'Grauflügel', NULL, CURRENT_TIMESTAMP, 0),
  ('35', '2', NULL, 'Hellflügel', NULL, CURRENT_TIMESTAMP, 0),
  ('36', '2', NULL, 'Falben', NULL, CURRENT_TIMESTAMP, 0),
  ('36', '3', NULL, 'Konti Schecken', NULL, CURRENT_TIMESTAMP, 0),
  ('36', '4', NULL, 'Schwarzaugen', NULL, CURRENT_TIMESTAMP, 0),
  ('36', '5', NULL, 'Hauben', NULL, CURRENT_TIMESTAMP, 0),
  ('37', '1', NULL, 'Paare 1,2,3,4,5,6,11,12,13', NULL, CURRENT_TIMESTAMP, 0),
  ('37', '2', NULL, 'Paare alle Übrigen', NULL, CURRENT_TIMESTAMP, 0),
  ('37', '3', NULL, 'Kollektionen 1,2,3,4,5,6,11,12,13', NULL, CURRENT_TIMESTAMP, 0),
  ('37', '4', NULL, 'Kollektionen alle Übrigen', NULL, CURRENT_TIMESTAMP, 0),
  ('38', '1', NULL, 'Neumutationen', NULL, CURRENT_TIMESTAMP, 0),
  ('4', '1', NULL, 'Zimt Opalin Grünreihe', NULL, CURRENT_TIMESTAMP, 0),
  ('4', '2', NULL, 'Zimt Opalin Blaureihe', NULL, CURRENT_TIMESTAMP, 0),
  ('5', '1', NULL, 'Opalin Grünreihe', NULL, CURRENT_TIMESTAMP, 0),
  ('5', '2', NULL, 'Opalin Blaureihe', NULL, CURRENT_TIMESTAMP, 0),
  ('6', '1', NULL, 'Gelbgesicht Normal', NULL, CURRENT_TIMESTAMP, 0),
  ('6', '2', NULL, 'Gelbgesicht Zimt', NULL, CURRENT_TIMESTAMP, 0),
  ('6', '3', NULL, 'Gelbgesicht Zimt Opalin', NULL, CURRENT_TIMESTAMP, 0),
  ('7', '1', NULL, 'Lutino', NULL, CURRENT_TIMESTAMP, 0),
  ('7', '2', NULL, 'Albino', NULL, CURRENT_TIMESTAMP, 0),
  ('8', '1', NULL, 'Lacewing Gelb', NULL, CURRENT_TIMESTAMP, 0),
  ('8', '2', NULL, 'Lacewing Weiß', NULL, CURRENT_TIMESTAMP, 0),
  ('9', '1', NULL, 'Aufghellt Gelb', NULL, CURRENT_TIMESTAMP, 0),
  ('9', '2', NULL, 'Aufgehellt Weiß', NULL, CURRENT_TIMESTAMP, 0);