# ============================================================
# Produktionsprofil - PostgreSQL auf Render
# ============================================================

# Datenbank (Werte kommen aus Render Umgebungsvariablen)
spring.datasource.url=jdbc:postgresql://dpg-d84b7fd7vvec73f52ksg-a.oregon-postgres.render.com:5432/wellensittich_db
spring.datasource.username=wellensittich_db_user
spring.datasource.password=J2GEOdgY57nHcJJLMFMhnrsLiOZhDwhe
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# H2 Console deaktivieren
spring.h2.console.enabled=false

# Liquibase
spring.liquibase.enabled=true